INSERT INTO estoque (tipo, quantidade) VALUES
('Caneta esferográfica azul', 100),
('Caneta esferográfica preta', 100),
('Lápis preto nº 2', 80),
('Borracha branca', 50),
('Apontador com depósito', 40),
('Clips para papel (caixa 100un)', 30),
('Grampeador médio', 15),
('Grampos para grampeador (caixa 1000un)', 20),
('Tesoura escolar', 10),
('Régua 30cm', 10),
('Cola bastão 40g', 25),
('Fita adesiva transparente', 30),
('Papel sulfite A4 (resma 500fl)', 50),
('Papel A4 reciclado (resma 500fl)', 20),
('Pasta suspensa plástica', 40),
('Pasta arquivo polionda', 35),
('Bloco de notas adesivas (Post-it)', 25),
('Agenda 2026 capa dura', 10),
('Marcador permanente preto', 30),
('Pincel atômico azul', 25);
